version: "1.0"
name: drf-test
services:
  server:
    image: python:latest
    volumes:
      - .:/app
    working_dir: /app
    command: python manage.py runserver
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - default

  database:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=chatbot
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --timezone=Asia/Seoul
    networks:
      - default

networks:
  default: